apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mlops
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'kubernetes-ml-service'
        scrape_interval: 5s
        metrics_path: '/metrics'
        static_configs:
          - targets: ['ml-service.mlops.svc.cluster.local:8000']
            labels:
              app: 'ml-credit-service'
              env: 'kubernetes-cluster'

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
