global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ml-service'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ml-service:8000']
        labels:
          app: 'credit-default-service'
          env: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
