"""
Prometheus Metrics Instrumentation for Model Serving and Drift Monitoring.
"""

import time
from typing import Any, Dict

from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    REGISTRY,
    generate_latest,
    CONTENT_TYPE_LATEST,
)

# -----------------
# Traffic & Latency Metrics
# -----------------
REQUESTS_TOTAL = Counter(
    "ml_requests_total",
    "Total HTTP requests received",
    ["endpoint", "method", "status"],
)

PREDICTIONS_TOTAL = Counter(
    "ml_predictions_total",
    "Total model predictions generated",
    ["model_version", "predicted_class"],
)

PREDICTION_LATENCY = Histogram(
    "ml_prediction_latency_seconds",
    "Time spent calculating model predictions",
    ["model_version"],
    buckets=[0.002, 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 1.0, 2.5],
)

PREDICTION_PROBABILITY = Histogram(
    "ml_prediction_probability",
    "Distribution of predicted probabilities for positive class (default)",
    ["model_version"],
    buckets=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
)

PREDICTION_ERRORS_TOTAL = Counter(
    "ml_prediction_errors_total",
    "Total prediction failures or validation errors",
    ["error_type"],
)

BUFFER_SIZE = Gauge(
    "ml_production_buffer_size",
    "Current number of requests stored in the drift evaluation sliding window",
)

# -----------------
# Drift Metrics
# -----------------
DATASET_DRIFT_DETECTED = Gauge(
    "ml_dataset_drift_detected",
    "Binary flag indicating whether dataset-level drift threshold is breached (1=drifted, 0=normal)",
)

DRIFT_SHARE = Gauge(
    "ml_drift_share",
    "Fraction of features currently flagged as drifted (0.0 to 1.0)",
)

DRIFTED_FEATURES_COUNT = Gauge(
    "ml_drifted_features_count",
    "Total number of features showing statistical drift",
)

FEATURE_DRIFT_DETECTED = Gauge(
    "ml_feature_drift_detected",
    "Flag indicating if a specific feature has drifted (1=drifted, 0=normal)",
    ["feature"],
)

FEATURE_DRIFT_P_VALUE = Gauge(
    "ml_feature_drift_p_value",
    "Kolmogorov-Smirnov test p-value for the feature (lower means more significant drift)",
    ["feature"],
)

FEATURE_DRIFT_KS_STAT = Gauge(
    "ml_feature_drift_ks_stat",
    "Kolmogorov-Smirnov test statistic for the feature",
    ["feature"],
)

FEATURE_DRIFT_PSI = Gauge(
    "ml_feature_drift_psi",
    "Population Stability Index (PSI) for the feature (>=0.2 indicates significant drift)",
    ["feature"],
)

FEATURE_CURRENT_MEAN = Gauge(
    "ml_feature_current_mean",
    "Mean value of the feature in the current production sliding window",
    ["feature"],
)

FEATURE_REFERENCE_MEAN = Gauge(
    "ml_feature_reference_mean",
    "Mean value of the feature in the baseline reference training dataset",
    ["feature"],
)

DRIFT_EVAL_TIMESTAMP = Gauge(
    "ml_drift_last_evaluated_timestamp_seconds",
    "Epoch timestamp when drift was last evaluated",
)


def update_prometheus_drift_metrics(drift_report: Dict[str, Any]) -> None:
    """
    Updates all Prometheus drift-related gauges based on the report generated by DriftDetector.
    """
    if drift_report.get("status") != "evaluated":
        return

    DATASET_DRIFT_DETECTED.set(1.0 if drift_report["dataset_drift_detected"] else 0.0)
    DRIFT_SHARE.set(drift_report["drift_share"])
    DRIFTED_FEATURES_COUNT.set(drift_report["drifted_features_count"])
    DRIFT_EVAL_TIMESTAMP.set(time.time())

    features = drift_report.get("features", {})
    for feat_name, feat_data in features.items():
        FEATURE_DRIFT_DETECTED.labels(feature=feat_name).set(
            1.0 if feat_data["drift_detected"] else 0.0
        )
        FEATURE_DRIFT_P_VALUE.labels(feature=feat_name).set(feat_data["p_value"])
        FEATURE_DRIFT_KS_STAT.labels(feature=feat_name).set(feat_data["ks_statistic"])
        FEATURE_DRIFT_PSI.labels(feature=feat_name).set(feat_data["psi"])
        FEATURE_CURRENT_MEAN.labels(feature=feat_name).set(feat_data["curr_mean"])
        FEATURE_REFERENCE_MEAN.labels(feature=feat_name).set(feat_data["ref_mean"])


def get_metrics_payload() -> bytes:
    """
    Serializes registry metrics in Prometheus text format.
    """
    return generate_latest(REGISTRY)
